namespace Component
{
    runtimeclass Class
    {
        Class();
        Class(String a);

        static String StaticMethod();

        Class ReturnObject();

        String Method();

        String Property;
    }

    delegate void Delegate(String arg);
}
