namespace Component
{
    [Windows.Foundation.Metadata.FastAbiAttribute]
    runtimeclass Class
    {
        Class(String a);

        static String StaticMethod();

        String Method();

        String Property;
    }

    delegate void Delegate(String arg);
}
